name = "virtual-trading-platform-admin"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./web/dist"
entry-point = "."

[build]
command = "cd web && npm install && npm run build"
watch_dir = "./web/dist"

# 添加环境变量
[vars]
VITE_API_BASE = "https://api.jcstjj.top"

# 添加自定义路由，优先使用优化的Cloudflare管理面板
[[routes]]
pattern = "/admin"
zone_id = ""
service = "virtual-trading-platform-admin"

[[routes]]
pattern = "/admin/*"
zone_id = ""
service = "virtual-trading-platform-admin"