apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-platform
  labels:
    app: trading-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trading-platform
  template:
    metadata:
      labels:
        app: trading-platform
    spec:
      containers:
      - name: app
        image: trading-platform:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_HOST
          value: "mysql-service"
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_USER
          value: "trading_user"
        - name: DATABASE_PASSWORD
          value: "trading_password"
        - name: DATABASE_NAME
          value: "virtual_trading_platform"
        - name: JWT_SECRET
          value: "virtual_trading_platform_secret_key_2025"
        volumeMounts:
        - name: data-storage
          mountPath: /app/data
        - name: backup-storage
          mountPath: /app/backups
        - name: log-storage
          mountPath: /app/logs
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: data-pvc
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pvc
      - name: log-storage
        persistentVolumeClaim:
          claimName: log-pvc