apiVersion: v1
kind: Service
metadata:
  name: trading-platform-service
spec:
  selector:
    app: trading-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer